name: Build Project

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
        build_type: [ Release ]
        compiler: [ gcc, clang ]
        include:
          - compiler: gcc
            c_compiler: gcc-13
            cpp_compiler: g++-13
          - compiler: clang
            c_compiler: clang-19
            cpp_compiler: clang++-19

    steps:
      - uses: actions/checkout@v4

      # the project is depended on GoogleTest
      - name: Resolve Dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt update
          sudo apt install -y ${{ matrix.c_compiler }} ${{ matrix.cpp_compiler }} libgtest-dev

      - name: Configure
        run: |
          cmake -E make_directory ${{ github.workspace }}/build
          cmake -B ${{ github.workspace }}/build                \
                -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}     \
                -DCMAKE_COLOR_DIAGNOSTICS=ON                    \
                -DCMAKE_CXX_FLAGS="-fdiagnostics-color=always"  \
                -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }} \
                -DCMAKE_C_COMPILER=${{ matrix.c_compiler }}     \
                -S ${{ github.workspace }}

      - name: Build
        working-directory: ${{github.workspace}}/build
        run: cmake --build . --config ${{ matrix.build_type }}

      - name: Run Tests
        working-directory: ${{ github.workspace }}/build
        run: ctest --output-on-failure
